/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ElEMss: typeof import('element-plus/es')['ElEMss']
  const ElMEss: typeof import('element-plus/es')['ElMEss']
  const ElMe: typeof import('element-plus/es')['ElMe']
  const ElMess: typeof import('element-plus/es')['ElMess']
  const ElMessage: typeof import('element-plus/es')['ElMessage']
  const ElMessageBox: typeof import('element-plus/es')['ElMessageBox']
}
